In [1]:
from matplotlib import pyplot as plt
import numpy as np
from mpl_toolkits.mplot3d import Axes3D

In [2]:
# d2 = [a/4,a/4,a/4]
# 1/delta[i,j]*(V1pseudo*(h[i]-h[j])+np.exp(-i*(h[i]-h[j]*d2)*V2pseudo))+ k[i] ** 2

In [3]:
# A = []
# A[i,j]=ki**2 * dij(i,j) + V1(hi-hj) + np.exp(-i*(hi-hj) * d2)*V2(hi-hj)

In [4]:
def dij(i,j):
    if i == j:
        return 1
    else:
        return 0

In [5]:
# define all h_i points

a = 10.26
r = (2 * np.pi)/a * np.sqrt(11)

rlv1 = [-2 * np.pi / a, 2 * np.pi / a, 2 * np.pi / a]
rlv2 = [2 * np.pi / a, -2 * np.pi / a, 2 * np.pi / a]
rlv3 = [2 * np.pi / a, 2 * np.pi / a, -2 * np.pi / a]

rlv1 = np.asarray(rlv1)
rlv2 = np.asarray(rlv2)
rlv3 = np.asarray(rlv3)

V = 4/3 * np.pi * r**3
# nh = r / rlv
h = []
for i in range(-3,4):
    h1 = rlv1 * i
#     print(h1)
    
    for j in range(-3,4):
        h2 = rlv2 * j
        
        for k in range(-3,4):
            h3 = rlv3 * k
            
            hv = h1 + h2 + h3
            hv = np.asarray(hv)
#             print(hv)
            if np.sqrt(np.dot(hv,hv)) <= r:
#                 print(hv)
                h.append(hv)
#                 print(h)
#                 print(hv)
h = np.asarray(h)
print(h)
# h = np.asarray(h)
# print(h)

# # for i in range(len(h)):
# print(h[:,0])
# #     print(h[i,0])

[[-0.61239623 -0.61239623 -1.83718869]
 [-0.61239623 -1.83718869 -0.61239623]
 [ 0.         -1.22479246 -1.22479246]
 [ 0.61239623 -0.61239623 -1.83718869]
 [ 0.61239623 -1.83718869 -0.61239623]
 [-1.83718869 -0.61239623 -0.61239623]
 [-1.22479246  0.         -1.22479246]
 [-0.61239623  0.61239623 -1.83718869]
 [-1.22479246 -1.22479246  0.        ]
 [-0.61239623 -0.61239623 -0.61239623]
 [ 0.          0.         -1.22479246]
 [ 0.61239623  0.61239623 -1.83718869]
 [-0.61239623 -1.83718869  0.61239623]
 [ 0.         -1.22479246  0.        ]
 [ 0.61239623 -0.61239623 -0.61239623]
 [ 1.22479246  0.         -1.22479246]
 [ 0.61239623 -1.83718869  0.61239623]
 [ 1.22479246 -1.22479246  0.        ]
 [ 1.83718869 -0.61239623 -0.61239623]
 [-1.83718869  0.61239623 -0.61239623]
 [-1.83718869 -0.61239623  0.61239623]
 [-1.22479246  0.          0.        ]
 [-0.61239623  0.61239623 -0.61239623]
 [ 0.          1.22479246 -1.22479246]
 [-0.61239623 -0.61239623  0.61239623]
 [ 0.          0.        

In [6]:
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

ax.scatter(h[:,0],h[:,1],h[:,2])
# plots the points described by vectors 'h' in 3d scatterplot
plt.show()